# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

# Challenge 1 - Matrix Functions

#### We would like to create our own matrix. To make life simple for us, we can represent matrices as a list of lists. For the sake of simplicity, we will assume that the maximum number of dimensions a matrix will have is 2.

The most basic thing we would like to do with two matrices is to add them together. To add two matrices, we must perform a number of checks. The first check we would like to perform is whether the matrix is two dimesional. This is because we want to limit ourselves to two dimensional matrices to simplify our problem. In the cell below write a function that checks is a matrix is two dimesional. 

In [130]:
def twodim(mat):
    # This function takes a list of lists and checks that it is of depth 2. 
    # If the depth is not 2, either return false or return informative errors that let the user know the depth of the list.
    # Input: nested list
    # Output: Boolean (or error)
    # Sample Input: [[1,2,3], [4,5,6]]
    # Sample Output: True
    
    # Your Code Here:
    if len(mat) == 2:
        return True
    else:
        return False
    


In [ ]:
twodim([[1,2],[1,2,3],[1,2,3]])

# Bonus Challenge 1 - Write the function recursively

Rewrite the `twodim` function using recursion. 
Read more about recursion [here](https://www.cs.utah.edu/~germain/PPS/Topics/recursion.html)

Hint: stop your recursion when there are no more lists, this wil be the depth of your matrix. Check that this depth is equal to 2.
Second Hint: At every level of the recursion, use the filter function to keep only the members of the list that are lists.

In [131]:
def twodimrecursive(mat):
    # Your code here:
    global contador
    contador += 1
    mat = list(filter(lambda x: isinstance(x, list), mat[1:]))  #istinance checa que x sea el tipo definido, en esta caso list
    if len(mat) > 0:                                            #para usar filter necesitas una función dentro, generalmente un booleano para que funcione
        twodimrecursive(mat)
    if contador == 2:
        return True
    else:
        return False
    

In [50]:
contador = 0
twodimrecursive([[1,2,3],[1,2]])

True

#### Next, we will write a function that checks for the number of rows and columns of a matrix. 

Recall that the outer list will tell us the number of rows and the inner lists will tell us the number of columns. Make sure that all inner lists are of the same length.

In [67]:

    # This function takes a list of lists and returns the size of the rows and the columns 
    # Input: list of lists
    # Output: Tuple of rows and columns
    #
    # Sample input: [[1,2,3],[4,5,6]]
    # Sample Output: (2, 3)
    
import numpy as np

#Ejemplo manual sin función
arr2D = np.array([[11 ,12,13,11], [21, 22, 23, 24], [31,32,33,34]])
print(arr2D)

# get number of rows in 2D numpy array
numOfRows = np.size(arr2D, 0)
#print(numOfRows)

#get number of columns
numOfCol = np.size(arr2D, 1)
#print(numOfCol)

#Producto final
arr2D_final = (numOfRows, numOfCol)
print(arr2D_final)   



[[11 12 13 11]
 [21 22 23 24]
 [31 32 33 34]]
(3, 4)


In [132]:
#Para convertirlo en función
def rowcolum(mat):
    arr2Dv = np.array(mat)
    numRows = np.size(arr2Dv, 0)
    numCols = np.size(arr2Dv, 1)
    return (numRows, numCols)


In [133]:
rowcolum([[1,2,3,4], [1,2,3,4],[1,2,3,4]])

(3, 4)

#### Our next step is to write a function that compares two matrices and tells us whether they are of equal size.

In this function we will check whether the number of rows and number of columns is the same.

In [138]:
#Este compare es el correcto
def compare(mat1, mat2):
    
    lista1=[]
    lista2=[]
    lista3=[]
    lista4=[]
   
    col=len(mat1)
    col2=len(mat2)
    cuenta=0
    cuenta2=0
    
    for x in mat1:
        cuenta=len(x)
        lista1.append(cuenta)        
        
    for y in mat2:
        cuenta2=len(y)
        lista2.append(cuenta2)   

            
    lista3.append(len(set(lista1)))
    lista3.append(col) 
    lista4.append(len(set(lista2)))
    lista4.append(col2) 
        
    if lista3==lista4:
        print("True")
    else:    

        return False

In [92]:
#Estas NO SON PARTE DEL EJECICIO. SON PRUEBAS INTERMEDIAS INTERESANTES

def compare1(mat1):
    #matriz1 = np.array(mat1)
    #matriz2 = np.array(mat2)
    if len(mat1[0]) == len(mat1[1]):
        return True
    else:
        return False
    # This function takes a two lists of lists and checks whether they have the same number of rows and columns
    # Input: two list of lists
    # Output: True or False
    #
    # Sample input: [[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]
    # Sample Output: True
    
    # Your code here:
#def compare(mat1, mat2):   
mat1 = [[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]
#print(compare(mat1))


#intento 2 de función
def compare2(mat1b, mat2b):
    mat1b = []
    mat2b = []
    if len(mat1b) == len(mat2b):
        return True
    else:
        return False
    
mat1b = [[1,2,3],[4,5,6]]
mat2b = [[7,8,9], [10,11,12]]

#print(compare2(mat1b, mat2b))

#Intento tres, que este sí define columnas y filas
mat1c = [[1,2,3],[4,5,6]]
mat2c = [[7,8,9], [10,11,12]]

#len(mat1c) == len(mat2c)       #comprobaciones de filas
#len(mat1c[0]) == len(mat2c[0]) #comprobaciones de columnas

def compare3(mat1c, mat2c):
    if len(mat1c) == len(mat2c) and len(mat1c[0]) == len(mat2c[0]):
        return True
    else:
        False


mat1c = [[1,2,3], [4,5,6]]
mat2c = [[7,8,9], [10,11,12]] 

print(compare3(mat1c, mat2c))
        
#def compare3(mat1c, mat2c):
#rows = len(group1)
#columns = len(group1[0])



True


In [139]:
compare([[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]])

True


#### Now that we have all the tools we need, write a function that adds two matrices together. 

Remember that a matrix is represented as a list of lists. Therefore, we must add each element in the list. The plus symbol is used for concatenating two lists and not for adding every element in two lists.

In [ ]:
#Esta es el addition que sí funciona
def addition3(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    return mat1 + mat2

addition3([[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]])

In [35]:
#Esto no importa, no es parte del ejercicio
import numpy as np
result = [[0,0,0], [0,0,0]]
#print(result[-1][-1])

#def addition(mat1, mat2):
    # This function takes a two lists of lists and adds each cell together
    # Input: two list of lists
    # Output: one summed list of lists
    #
    # Sample input: [[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]
    # Sample Output: [[8,10,12],[14,16,18]]
    
    # Your code here:
    #result = [[0,0,0], [0,0,0]]
    #for x in range(len(mat1)):                  #iterar las filas
    #    for y in range(len(mat1[0])):           #iterar las columnas
    #        result[x][y] = mat1[x][y] + mat2[x][y]
    #for r in result:
    #    result.append(r)
    #    return r

            
            
#Comprobación manual
mat1 = [[1,2,3],[4,5,6]]
mat2 = [[7,8,9], [10,11,12]]

for x in range(len(mat1)):                  #iterar las filas
    for y in range(len(mat1[0])):           #iterar las columnas
        result[x][y] = mat1[x][y] + mat2[x][y]

for r in result:
    matrix_final = []
    matrix_final.append(r)
    print(matrix_final)
    
#https://www.programiz.com/python-programming/examples/add-matrix
# iterate through rows
#for i in range(len(X)):
   # iterate through columns
#   for j in range(len(X[0])):
#       result[i][j] = X[i][j] + Y[i][j]        

[[8, 10, 12]]
[[14, 16, 18]]


In [37]:
#Esto tampoco importa

#mat1 = [[1,2,3],[4,5,6]]
#mat2 = [[7,8,9], [10,11,12]]
#matrizsumada = [map(sum, zip(*t)) for t in zip(mat1, mat2)]
#print(matrizsumada)
def addition2(mat1, mat2):
    result = [[0,0,0], [0,0,0]]
    for x in range(len(mat1)):                  #iterar las filas
        for y in range(len(mat1[0])):           #iterar las columnas
            result[x][y] = mat1[x][y] + mat2[x][y]

    for r in result:
        matrix_final = []
        matrix_final.append(r)
        return matrix_final

addition2([[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]) #sólo arroja una lista, está mal

[[8, 10, 12]]

In [141]:
print(addition3([[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]))

[[ 8 10 12]
 [14 16 18]]


# Challenge 2 - Creating the Class

In the cell below, you will be creating the class Matrix2D. Use the functions you have written above and tweak them according to the instructions in the comments. You got this!

In [116]:
class Matrix2D:
    # First, we will write the __init__ function. 
    # In this function, we will initialize rows and the columns using the matrix that we have passed to the class.
    
    def __init__(self, mat):             #aquí se define lo que quieres poner en la clase y que debes definir
        # Assign mat to self.mat
        # Assign rows and cols to self.rows and self.cols
        # To find the rows and the cols, use the rowcolumn function and pass self.mat to the function.
        # Since the rowcolumn function is now a member of the class, make sure to refer to the function as self.rowcolumn
        
        # Your code here:
        self.mat = mat
        self.cols = None
        self.rows = None
        #self.rowcolum(self, mat) 

            
        #self.cols = len(self)
        #self.rows = len(self[i])
    
    # Insert the twodim function here.
    # The only change you need to make is that now we are passing self and mat to the function (make sure self is first).
    
    # Your code here:
    def twodim(self, mat):
        if len(mat) == 2:
            return True
        else:
            return False
        
        #for elem in mat:
        #    if(isinstance(elm[0], list)):
        #        return False
        #return True
    
    # Insert the rowcolumn function here.
    # The changes you need to make: 
    # 1. The function now takes self and mat as arguments (make sure to pass self first).
    # 2. Any reference to twodim will be changed to self.twodim since this function is a member of the class and takes self 
    
    # Your code here:
    def rowcolum(self, mat):
        arr2Dv = np.array(mat)
        numRows = np.size(arr2Dv, 0)
        numCols = np.size(arr2Dv, 1)
        return (numRows, numCols)

    
    #def rowcolumns(self, mat):
    #    cols = len(mat)
    #    rows = len(mat[0])
    #    while len(cols) > len(rows):
    #        for i in mat:
    #            for j in mat:
    #                if len(i) > len(j):
    #                    row += 1
    #                    return (cols, rows)
  

    # Insert the compare function here
    # Add self as the first argument passed to the function
    
    # Your code here:
    def compare(self, mat1, mat2):
        lista1=[]
        lista2=[]
        lista3=[]
        lista4=[]
        
        col=len(mat1)
        col2=len(mat2)
        cuenta=0
        cuenta2=0
    
        for x in mat1:
            cuenta=len(x)
            lista1.append(cuenta)        
        
        for y in mat2:
            cuenta2=len(y)
            lista2.append(cuenta2)   

            
        lista3.append(len(set(lista1)))
        lista3.append(col) 
        lista4.append(len(set(lista2)))
        lista4.append(col2) 
        
        if lista3==lista4:
            return True
        else:
            return False


    # Insert the addition function here
    # This function now takes self and matrix (another matrix of the Matrix2D class)
    # Change the compare function to self.compare 
    # Change any reference to mat1 and mat2 to self.mat and matrix.mat respectively
    # Return your result as a Matrix2D(result). This will ensure that we return a new matrix and not a list of lists.
    
    # Your code here:
    def addition(self, matrix):
        return Matrix2D(np.add(self.mat,matrix.mat))

In [125]:
#Otra forma

class Matrix2D_2:
    # First, we will write the __init__ function. 
    # In this function, we will initialize rows and the columns using the matrix that we have passed to the class.
    
    def __init__(self, mat):             #aquí se define lo que quieres poner en la clase y que debes definir
        # Assign mat to self.mat
        # Assign rows and cols to self.rows and self.cols
        # To find the rows and the cols, use the rowcolumn function and pass self.mat to the function.
        # Since the rowcolumn function is now a member of the class, make sure to refer to the function as self.rowcolumn
        
        # Your code here:
        self.mat = mat
        self.cols = None
        self.rows = None
        #self.rowcolum(self, mat) 

    
    # Insert the twodim function here.
    # The only change you need to make is that now we are passing self and mat to the function (make sure self is first).
    
    # Your code here:
    def twodim(self):
        if len(self.mat) == 2:
            return True
        else:
            return False
        
        #for elem in mat:
        #    if(isinstance(elm[0], list)):
        #        return False
        #return True
    
    # Insert the rowcolumn function here.
    # The changes you need to make: 
    # 1. The function now takes self and mat as arguments (make sure to pass self first).
    # 2. Any reference to twodim will be changed to self.twodim since this function is a member of the class and takes self 
    
    # Your code here:
    def rowcolum(self):
        arr2Dv = np.array(self.mat)
        numRows = np.size(arr2Dv, 0)
        numCols = np.size(arr2Dv, 1)
        return (numRows, numCols)

    
    #def rowcolumns(self, mat):
    #    cols = len(mat)
    #    rows = len(mat[0])
    #    while len(cols) > len(rows):
    #        for i in mat:
    #            for j in mat:
    #                if len(i) > len(j):
    #                    row += 1
    #                    return (cols, rows)
  

    # Insert the compare function here
    # Add self as the first argument passed to the function
    
    # Your code here:
    def compare(self, mat2):    #self contiene mat1, sólo se tiene que igresar mat2
        lista1=[]
        lista2=[]
        lista3=[]
        lista4=[]
        
        col=len(self.mat)
        col2=len(mat2)
        cuenta=0
        cuenta2=0
    
        for x in self.mat:
            cuenta=len(x)
            lista1.append(cuenta)        
        
        for y in mat2:
            cuenta2=len(y)
            lista2.append(cuenta2)   

            
        lista3.append(len(set(lista1)))
        lista3.append(col) 
        lista4.append(len(set(lista2)))
        lista4.append(col2) 
        
        if lista3==lista4:
            return True
        else:
            return False


    # Insert the addition function here
    # This function now takes self and matrix (another matrix of the Matrix2D class)
    # Change the compare function to self.compare 
    # Change any reference to mat1 and mat2 to self.mat and matrix.mat respectively
    # Return your result as a Matrix2D(result). This will ensure that we return a new matrix and not a list of lists.
    
    # Your code here:
    def addition(self, matrix):
        return np.add(self.mat,matrix)

In [121]:
Matrix2D_2([[1,2,3],[4,5,6]]).addition(Matrix2D_2([[7,8,9],[10,11,12]])).mat

array([[ 8, 10, 12],
       [14, 16, 18]])

In [129]:
matriz1 = Matrix2D_2([[1,2,3],[4,5,6]])
matriz2 = [[7,8,9],[10,11,12]]              #esto ya es un array
matriz3 = Matrix2D_2([[7,8,9],[10,11,12]])  #esto es un objeto distinto, por lo tanto hay que declarlo como matriz

print(matriz1.addition(matriz2))
print(matriz1.addition(matriz3.mat))

[[ 8 10 12]
 [14 16 18]]
[[ 8 10 12]
 [14 16 18]]


In [114]:
Matrix2D([[1,2,3],[4,5,6]]).addition(Matrix2D([[7,8,9],[10,11,12]])).mat

array([[ 8, 10, 12],
       [14, 16, 18]])

# Bonus Challenge 2 - Transpose Function

#### Write a function that transposes the matrix and add it to your class.

You can read more about the transpose of a matrix [here](https://en.wikipedia.org/wiki/Transpose).

Hint: Use the zip function. Read about it [here](https://docs.python.org/3.3/library/functions.html#zip)

Second Hint: Read about the asterisk in Python [here](https://docs.python.org/3/reference/expressions.html#expression-lists)

In [ ]:
def transpose(mat):
    # This function takes a list of lists and returns a transposed list of lists.
    # Input: list of lists
    # Output: list of lists
    
    # Sample Input: [[1,2,3],[4,5,6]]
    # Sample Output: [[1,4], [2,5], [3,6]]
    
    # Your code here:
    

In [ ]:
transpose([[1,2,3],[4,5,6]])